version: "3.9"
services:
  gen-template:
    image: python:3.11
    volumes:
      - .:/workarea
    working_dir: /workarea
    command: bash -c "python scripts/gen_template.py -g ${GRIND} -s ${SOLUTION}"
  utest:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    volumes:
      - .:/workarea
      - ./build:/buildarea:cached
    working_dir: /workarea
    command: bash -c "
      cmake -B /buildarea -S /workarea 
      && cd /buildarea 
      && make 
      && ctest
      "